### ISSUE TITLE
Write and schedule first crawlers for New Zealand

### ISSUE THREAD

**Issue by ojongerius** [volCommunity/vol-crawlers#1]
Initially adding:
* https://seekvolunteer.co.nz/volunteering

- [x] Crawler for Seek coded up
- [x] Seek gigs synched to localhost as POC
- [x] Seek gigs synched to prod
- [x] Crawler scheduled
- [ ] Crawler has unit tests and or contracts

Things that came up and need a resolution:
- [x] Labels are not lowercased in REST, but are when doing comparison on site. https://github.com/volCommunity/vol-django/issues/40
- [x] Ditto for locations. https://github.com/volCommunity/vol-django/issues/41
- [ ] Puling spider logic of Seek out into separate repo could be a  good move, same for others https://github.com/volCommunity/vol-crawlers/issues/9
- [ ] Region is never actually used, and not readily available from Seek. Should we remove it from the models? https://github.com/volCommunity/vol-django/issues/42
- [ ] We probably want an expiration date. Although we could use created_at and updated_at for this. https://github.com/volCommunity/vol-django/issues/43
- [ ] Crawlers need contracts and or integration tests with Django. https://github.com/volCommunity/vol-django/issues/40

**Comment by ojongerius** [comment]
Ready to start actually doing this work in a nice way after implementing REST endpoints (https://github.com/volCommunity/vol-django/issues/4), adding API key (https://github.com/volCommunity/vol-django/issues/7) support and enabling HTTPS (https://github.com/volCommunity/vol-django/issues/3).

**Comment by ojongerius** [comment]
While coding this up, found I needed to some more work on the Django side; added support for filtering on REST endpoints, and foreign key constraints on models to prevent recreating the same objects (with new IDs) over and over again. See https://github.com/volCommunity/vol-django/pull/33

**Comment by ojongerius** [comment]
Raised #8 for dogoodjobs. Code for seek is in PR, but want to solve a few issues I encountered before moving on another source.

**Comment by ojongerius** [comment]
First crawler works, but a few things need resolving, have added those to the original body.

**Comment by ojongerius** [comment]
Deploy to scrapyinghub is a bit sucky:
* Github support needs scrapy.cfg in root of repo, and wants admin access to webhooks and services (see https://support.scrapinghub.com/support/solutions/articles/22000201935-deploying-a-project-from-a-github-repository )
* Shub ( https://github.com/scrapinghub/shub ) does not really seem to be made for environments like Travis. 

Shub does support a config file and setting of an apikey, so we could use cookiecutter, or old school sed to set the API key and run the deploy for us.

**Comment by ojongerius** [comment]
Deployed spider to https://app.scrapinghub.com/p/247498 which will be updated by merges to master.

Daily runs have been scheduled, but payment / subscription needs to clear before they will be executed.

**Comment by ojongerius** [comment]
Am closing this one; spiders deployed, did run and have been scheduled. Issues found while working on it have been opened and will be taken care of when there is nothing more important to do.
